import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport:{width:1600,height:1000} });
p.on("response", r => { if (r.url().includes("/api/")) console.log(r.status(), r.url().replace("http://localhost:5210","")); });
p.on("requestfailed", r => console.log("FAIL", r.url(), r.failure()?.errorText));
await p.goto("http://localhost:5210/", { waitUntil:"domcontentloaded" });
await p.waitForTimeout(1500);
const u = p.locator('input').first(); await u.click(); await u.type("ernesto");
const pw = p.locator('input[type="password"]').first(); await pw.click(); await pw.type("brote-8039");
await p.keyboard.press("Enter");
await p.waitForTimeout(12000);
await b.close();
